# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: false
font: 'minimal'
font_size: M

# SEO

site_type: EducationalOrganization
local_business_type: ''
org_name: 'Center Synergy of Systems'
description: 'Center Synergy of Systems, Department of the Center of Interdisciplinary Digital Science (CIDS)'
keywords: ''
twitter: ''

# Contact (edit or remove options as required)

email: synosys@tu-dresden.de
#phone: +49 (0) 30 18754 20 70
#address:
#  street: Georg-Schumann-Str. 7
#  city: Dresden
#  region: Saxony
#  postcode: '10115'
#  country: Germany
#  country_code: DE
coordinates:
  latitude: '51.02759213464411'
  longitude: '13.72204359748961'
directions: Georg-Schumann-Str. 7a, 01069 Dresden
#office_hours:
#  - 'Monday 10:00 to 13:00'
#  - 'Wednesday 09:00 to 10:00'
#appointment_url: 'https://calendly.com'
#contact_links:
#  - icon: twitter
#    icon_pack: fab
#    name: Follow Me
#    link: 'https://twitter.com/DirkBrockmann'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Mon, 2. Jan 2006'
time_format: '15:04'
address_format: de

# Site features

highlight: true
highlight_languages:
  - r
math: true
diagram: false
privacy_pack: true
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: false
  publication: true
  event: true
reading_time: false
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 150
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: p4
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: ''
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'UA-46302068-1'
  google_tag_manager: ''
  google_site_verification: '9dEOVEaB7qydj0YBXH6OlvzWEKqwTom1RALsevenjZk'
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    fab: true
    fas: true
    ai: true
