const html=require("nanohtml"),loadData=require("./src/load-data.js"),createChart=require("./src/chart.js"),{config:config,getDate:getDate}=require("./src/config.js");function initChart({data:t,dates:e}){const a={dataset:"k_std_",sync:!1},n=(t[0],html`<div style="display:flex; flex-wrap:wrap; overflow-y:auto; overflow-x: hidden; height:calc(100% - 40px);"></div>`),o=["k_std_","k_"].map((t,e)=>html`<div class="button ${t===a.dataset?"selected":""}" onclick=${()=>r(t,e)}>${config[t].label}</div>`),c=html`<input style="margin-left:20px;" type="checkbox" id="sync" name="sync" checked=${a.sync} onchange=${t=>{var e;e=t.target.checked,a.sync=e,h()}}>`,s=html`
        <div style="display:flex;align-items:center;height:40px"> 
            <div class="title">${config.title}</div> 
            ${o}
            ${c}
            <label>${config.syncLabel}</label>
        </div>`;let d=Math.max(window.innerWidth/4,200)-20,l=uPlot.sync("test");const i=t.map((a,o)=>{document.createElement("div").style.width=`${d}px`;const c=[e,a.data.k_std_,a.data.k_std__7davg],s=createChart(c,{w:d,h:200,parent:n,sync:l,label:a.label,index:o,onCursorUpdate:0==o?t=>{!function(t){const e=getDate(!0,i[0].data[0][t]);i.forEach(a=>{a.updateLegend(t,e)})}(t)}:()=>{},onSelectUpdate:o==t.length-1?t=>{h()}:()=>{}});return l.sub(s),window.chart=s,s});function r(n,c){const{color:s,transparentColor:d}=config[n];a.dataset=n,o.forEach(t=>{t.classList.remove("selected"),t.style.backgroundColor=""}),o[c].classList.add("selected"),o[c].style.backgroundColor=d,i.forEach((a,o)=>{const c=t[o];a.setData([e,c.data[n],c.data[`${n}_7davg`]]),a.updateColor(s,d)})}function h(){setTimeout(()=>{const t=i[0].series[0].idxs,e=t[0],n=t[1];let o=0,c=1e3;!0===a.sync?(i.forEach(t=>{const a=t.data[2];let s=a[e],d=a[e],l=e;for(;l<=n;)null===d&&(d=a[l]),a[l]<d&&(d=a[l]),a[l]>s&&(s=a[l]),l++;s>o&&(o=s),d<c&&(c=d)}),o+=2,c>2&&(c-=2),c=0,i.forEach(t=>{t.updateYRange(c,o),t.setScale("y",{min:c,max:o})})):(console.log("autoscaling",e,n),i.forEach(t=>{const a=t.data[2];let o=a[e],c=a[e],s=e;for(;s<=n;)null===c&&(c=a[s]),a[s]>o&&(o=a[s]),a[s]<c&&(c=a[s]),s++;o+=2,c>2&&(c-=2),t.updateYRange(c,o),t.setScale("y",{min:c,max:o})}))},50)}function u(){let t=200,e=window.innerWidth;t=e<600?e/2-20:e<700?e/3-15:e/4-20;i.forEach((e,a)=>{e.updateSize(t,180)})}window.addEventListener("resize",()=>{u()});const f=html`<div style="height:100%;position:absolute">
    ${s}
    ${n}
    </div>`;document.body.appendChild(f),r("k_std_",0),u()}loadData(`contactindex-data/data/cx_state_processed.csv?${Math.floor(1e3*Math.random())}`,t=>{initChart(t)});